from enum import Enum


class GlobalErrorMessages(Enum):
    AdditionOperationError = 'Expression with plus sign is wrong!'
    SubtractionOperationError = 'Expression with minus sign is wrong!'
    MultiplicationOperationError = 'Expression with multiplying sign is wrong!'
    DivisionOperationError = 'Expression with dividing sign is wrong!'
    MaxOperationError = 'Expression for searching max value is wrong!'
    MinOperationError = 'Expression for searching min value is wrong!'
    ExponentiantOperationError = 'Expression with exponent sign is wrong!'
    ReplacementError = 'Expression for replacing the cell is wrong!'
    GetCellTextError = 'Something wrong with data in cell or you input not existing cell'
    AddingRowError = 'When adding new row something went wrong'
    AddingColError = 'When adding new col something went wrong'
    DeletingRowError = 'When delete row something went wrong'
    DeletingColError = 'When delete col something went wrong'
    ParsingError = 'When parsing something went wrong'
    CellParsingError = 'When parsing cell something went wrong'
    LineParsingError = 'When parsing line something went wrong'
    ReplacementParsingError = 'When parsing replacement something went wrong'
    CellCalculationError = 'When calculating cell something went wrong'
    CellComparingError = 'When comparing cell something went wrong'
    FillLineError = 'When filling line something went wrong'
    ClearLineError = 'When clear line something went wrong'
    AboutProjectMsgError = 'When open about_project dialog something went wrong'
    CellIsNotSelectedMsgError = 'When open cell_is_not_selected dialog something went wrong'
    ExpressionFieldIsEmptyMsgError = 'When open expression_field_is_empty dialog something went wrong'
    WrongFileFormatMsgError = 'When open wrong_file_format dialog something went wrong'
    SetPathError = 'When set the path something went wrong'
    GetWorkingSheetError = 'When get working sheet something went wrong'
